language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py35
            python: 3.5
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy
install: pip install coveralls tox
script: tox
after_success: TOP=. coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
